id: PCC00FCAC
initial_creation_type: input
source_metadata:
  title: Paramārthasāra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Marino Faliero
  contribution to GRETIL: Marino Faliero
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:05:31.924509'
last_modified_at: '2022-03-09T15:05:31.924522'
